"use client";
import {FormEvent,useEffect,useState} from "react";
type Item={id:string;name:string;sku:string;cat:string;stock:number;reorder:number;cost:number;price:number;location:string};
type Sale={id:string;itemId:string;item:string;qty:number;total:number;payment:string;customer:string;time:string;synced:boolean};
type Tab="Overview"|"POS"|"Inventory"|"Purchases"|"Customers"|"Suppliers"|"Expenses"|"Reports"|"Team"|"Settings";
const seed:Item[]=[];
const saleSeed:Sale[]=[];
const RESET_VERSION="fresh-test-2026-08-17";
const tabs:Tab[]=["Overview","POS","Inventory","Purchases","Customers","Suppliers","Expenses","Reports","Team","Settings"];
const icon:Record<Tab,string>={Overview:"▦",POS:"⊕",Inventory:"□",Purchases:"⇩",Customers:"♙",Suppliers:"⌂",Expenses:"↗",Reports:"⌁",Team:"♚",Settings:"⚙"};
const gh=(n:number)=>`GH₵${n.toLocaleString(undefined,{minimumFractionDigits:2})}`;
export default function Home(){const[tab,setTab]=useState<Tab>("Overview"),[online,setOnline]=useState(true),[items,setItems]=useState(seed),[sales,setSales]=useState(saleSeed),[modal,setModal]=useState<"sale"|"item"|null>(null),[toast,setToast]=useState(""),[query,setQuery]=useState(""),[ready,setReady]=useState(false);
useEffect(()=>{const f=()=>setOnline(navigator.onLine);f();addEventListener("online",f);addEventListener("offline",f);return()=>{removeEventListener("online",f);removeEventListener("offline",f)}},[]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(t)}},[toast]);
useEffect(()=>{const r=indexedDB.open("cflex-store",1);r.onupgradeneeded=()=>r.result.createObjectStore("state");r.onsuccess=()=>{const db=r.result,t=db.transaction("state","readwrite").objectStore("state");const resetKey="cflex-store-reset-version";if(localStorage.getItem(resetKey)!==RESET_VERSION){t.clear();t.put([],"items");t.put([],"sales");setItems([]);setSales([]);localStorage.setItem(resetKey,RESET_VERSION);setReady(true);return}let pendingReads=2;const done=()=>{pendingReads-=1;if(pendingReads===0)setReady(true)};t.get("items").onsuccess=e=>{const v=(e.target as IDBRequest).result;if(Array.isArray(v))setItems(v);done()};t.get("sales").onsuccess=e=>{const v=(e.target as IDBRequest).result;if(Array.isArray(v))setSales(v);done()}}},[]);
useEffect(()=>{if(!ready)return;const r=indexedDB.open("cflex-store",1);r.onsuccess=()=>{const t=r.result.transaction("state","readwrite").objectStore("state");t.put(items,"items");t.put(sales,"sales")}},[items,sales,ready]);
const revenue=sales.reduce((a,s)=>a+s.total,0),cogs=sales.reduce((a,s)=>a+(items.find(i=>i.id===s.itemId)?.cost||0)*s.qty,0),low=items.filter(i=>i.stock<=i.reorder),pending=sales.filter(s=>!s.synced).length,visible=items.filter(i=>(i.name+i.sku+i.cat).toLowerCase().includes(query.toLowerCase()));
const sync=async()=>{if(!online)return setToast("Offline records are safe and waiting");await new Promise(r=>setTimeout(r,350));setSales(v=>v.map(s=>({...s,synced:true})));setToast("Everything is synced")};
const openSale=()=>{if(!items.length)return setToast("Add a product before recording a sale");setModal("sale")};
return <main><aside><div className="brand"><b>C</b><span><strong>C.FLEX</strong><small>STORE MANAGER</small></span></div><nav>{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}><i>{icon[t]}</i>{t}{t==="Inventory"&&<em>{low.length}</em>}</button>)}</nav><div className="user"><b>SO</b><span><strong>Store Owner</strong><small>Owner · Main Store</small></span></div></aside><section className="work"><header><div className="mobile"><b>C</b><strong>C.FLEX</strong></div><span className={online?"status":"status offline"}>● {online?"Online · Synced":`Offline · ${pending} queued`}</span><button onClick={sync}>↻ Sync now</button></header><div className="content">
{tab==="Overview"&&<><Title title="Good morning." sub="Here’s how C.Flex is performing today." action="＋ Record sale" click={openSale}/><div className="stats"><Stat name="Today’s sales" value={gh(revenue)} note={sales.length?"Current recorded sales":"No sales recorded yet"}/><Stat name="Gross profit" value={gh(revenue-cogs)} note={revenue?`${Math.round((revenue-cogs)/revenue*100)}% margin`:"No sales yet"}/><Stat name="Stock value" value={gh(items.reduce((a,i)=>a+i.stock*i.cost,0))} note={`${items.reduce((a,i)=>a+i.stock,0)} units on hand`}/><Stat name="Needs attention" value={`${low.length} items`} note="Low stock or pending"/></div><div className="twocol"><Panel title="Sales overview"><div className="chart">{[45,68,55,83,64,92,76].map((h,i)=><span key={i} style={{height:h+"%"}}><small>{"SMTWTFS"[i]}</small></span>)}</div></Panel><Panel title="Low stock">{low.length?low.map(i=><div className="stock" key={i.id}><b>{i.cat[0]}</b><span><strong>{i.name}</strong><small>{i.sku} · {i.location}</small></span><em>{i.stock} left</em></div>):<p>No low-stock items.</p>}</Panel></div><Sales sales={sales}/></>}
{tab==="Inventory"&&<><Title title="Inventory" sub="Every item, variant and location in one reliable view." action="＋ Add product" click={()=>setModal("item")}/><div className="tools"><input placeholder="Search name, SKU, barcode or category…" value={query} onChange={e=>setQuery(e.target.value)}/><button>Category⌄</button><button>▣ Scan barcode</button></div><div className="panel scroll"><div className="table inventory"><div>Product</div><div>Category</div><div>Location</div><div>Stock</div><div>Cost</div><div>Price</div>{visible.flatMap(i=>[<span key={i.id+"a"}><b>{i.name}</b><small>{i.sku}</small></span>,<span key={i.id+"b"}>{i.cat}</span>,<span key={i.id+"c"}>{i.location}</span>,<span key={i.id+"d"}><em className={i.stock<=i.reorder?"warn":"ok"}>{i.stock} units</em></span>,<span key={i.id+"e"}>{gh(i.cost)}</span>,<strong key={i.id+"f"}>{gh(i.price)}</strong>])}</div>{!visible.length&&<p>No products yet. Use “Add product” to start your fresh store test.</p>}</div></>}
{tab==="POS"&&<><Title title="Point of Sale" sub="Fast barcode, search and offline checkout." action="＋ New sale" click={openSale}/><div className="products">{items.length?items.map(i=><button key={i.id} onClick={openSale}><b>{i.cat[0]}</b><strong>{i.name}</strong><small>{i.stock} available</small><em>{gh(i.price)}</em></button>):<p>No products available yet. Add inventory first.</p>}</div><Sales sales={sales}/></>}
{!["Overview","Inventory","POS"].includes(tab)&&<Module tab={tab}/>}</div><nav className="bottom">{(["Overview","POS","Inventory","Purchases","Reports"] as Tab[]).map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}><i>{icon[t]}</i><small>{t}</small></button>)}</nav></section>
{modal==="sale"&&items.length>0&&<SaleModal items={items} online={online} close={()=>setModal(null)} save={(s)=>{setSales(v=>[s,...v]);setItems(v=>v.map(i=>i.id===s.itemId?{...i,stock:i.stock-s.qty}:i));setModal(null);setToast(online?"Sale completed and synced":"Sale saved offline and queued")}}/>}{modal==="item"&&<ItemModal close={()=>setModal(null)} save={i=>{setItems(v=>[i,...v]);setModal(null);setToast("Product added")}}/>}{toast&&<div className="toast">✓ {toast}</div>}</main>}
function Title({title,sub,action,click}:{title:string;sub:string;action:string;click:()=>void}){return <div className="title"><div><small>Saturday, 1 August</small><h1>{title}</h1><p>{sub}</p></div><button onClick={click}>{action}</button></div>}function Stat({name,value,note}:{name:string;value:string;note:string}){return <article><small>{name}</small><h2>{value}</h2><p>{note}</p></article>}function Panel(p:{title:string;children:React.ReactNode}){return <section className="panel"><h3>{p.title}</h3>{p.children}</section>}
function Sales({sales}:{sales:Sale[]}){return <Panel title="Recent sales">{sales.length?<div className="table sales"><div>Sale</div><div>Product</div><div>Customer</div><div>Payment</div><div>Status</div><div>Total</div>{sales.map(s=>[<span key={s.id+1}><b>{s.id}</b><small>{s.time}</small></span>,<span key={s.id+2}>{s.item} × {s.qty}</span>,<span key={s.id+3}>{s.customer}</span>,<span key={s.id+4}>{s.payment}</span>,<span key={s.id+5}><em className={s.synced?"ok":"warn"}>{s.synced?"Synced":"Queued"}</em></span>,<strong key={s.id+6}>{gh(s.total)}</strong>])}</div>:<p>No sales recorded yet.</p>}</Panel>}
function Module({tab}:{tab:Tab}){const map:Record<string,[string,string[]]>={Purchases:["Purchase orders, shipments, receiving and landed cost.",["Open purchase orders","In transit","Goods receiving","Landed-cost allocation"]],Customers:["Profiles, credit, history and WhatsApp details.",["Customer directory","Balances & credit","Purchase history","Loyalty groups"]],Suppliers:["Compare cost, lead time, quality and category.",["Supplier registry","Performance score","Source evidence","Price history"]],Expenses:["Operating costs separate from inventory value.",["Operating expenses","Logistics","Rent & utilities","Payroll"]],Reports:["Sales and stock movements turned into decisions.",["Profit & loss","Best sellers","Slow stock","Restock forecast"]],Team:["Role-based access and a complete audit trail.",["Owner","Manager","Cashier","Activity log"]],Settings:["Warehouses, currencies, tax, barcode and sync.",["Locations & bins","GHS · CNY · USD · XOF","Barcode rules","Backup & sync"]]};const d=map[tab];return <><Title title={tab} sub={d[0]} action="＋ New record" click={()=>{}}/><div className="modules">{d[1].map(x=><Panel key={x} title={x}><p>Connected to inventory, finance and audit trail.</p><button>Open →</button></Panel>)}</div><div className="info"><b>Integrated workflow</b><p>Every change has a unique ID. Staff can work without internet, and records sync safely when connection returns without creating duplicates.</p></div></>}
function SaleModal({items,online,close,save}:{items:Item[];online:boolean;close:()=>void;save:(s:Sale)=>void}){const[id,setId]=useState(items[0].id),[qty,setQty]=useState(1),[payment,setPayment]=useState("Mobile Money"),[customer,setCustomer]=useState("Walk-in");const item=items.find(i=>i.id===id)!;return <Modal title="Record sale" close={close}><form onSubmit={(e:FormEvent)=>{e.preventDefault();if(qty<=item.stock)save({id:`S-${Date.now().toString().slice(-4)}`,itemId:id,item:item.name,qty,total:item.price*qty,payment,customer,time:"Just now",synced:online})}}><label>Product<select value={id} onChange={e=>setId(e.target.value)}>{items.map(i=><option value={i.id} key={i.id}>{i.name} — {i.stock} available</option>)}</select></label><div className="form2"><label>Quantity<input type="number" min="1" max={item.stock} value={qty} onChange={e=>setQty(+e.target.value)}/></label><label>Payment<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Mobile Money</option><option>Cash</option><option>Card</option><option>Store Credit</option></select></label></div><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)}/></label><h3>Total <b>{gh(item.price*qty)}</b></h3><button className="save">Complete sale</button></form></Modal>}
function ItemModal({close,save}:{close:()=>void;save:(i:Item)=>void}){const[name,setName]=useState(""),[sku,setSku]=useState(""),[stock,setStock]=useState(0),[cost,setCost]=useState(0),[price,setPrice]=useState(0);return <Modal title="Add product" close={close}><form onSubmit={e=>{e.preventDefault();save({id:crypto.randomUUID(),name,sku,stock,cost,price,cat:"Jewelry",reorder:5,location:"Shop · J1"})}}><label>Product name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>SKU or barcode<input required value={sku} onChange={e=>setSku(e.target.value)}/></label><div className="form2"><label>Opening stock<input type="number" value={stock} onChange={e=>setStock(+e.target.value)}/></label><label>Unit cost<input type="number" value={cost} onChange={e=>setCost(+e.target.value)}/></label></div><label>Selling price<input type="number" value={price} onChange={e=>setPrice(+e.target.value)}/></label><button className="save">Save product</button></form></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay"><div className="modal"><button className="x" onClick={close}>×</button><h2>{title}</h2><p>Changes update stock, cost and audit history automatically.</p>{children}</div></div>}
