"use client";
import {FormEvent,useEffect,useState} from "react";

type Item={id:string;name:string;sku:string;cat:string;stock:number;reorder:number;cost:number;price:number;location:string;image?:string};
type Sale={id:string;itemId:string;item:string;qty:number;total:number;payment:string;customer:string;time:string;synced:boolean};
type PurchaseLine={id:string;name:string;sku:string;qty:number;cost:number;price:number;cat:string;image?:string};
type Purchase={id:string;supplier:string;tracking:string;status:"Ordered"|"Received";time:string;lines:PurchaseLine[]};
type StoreProfile={name:string;logo?:string};
type Tab="Overview"|"POS"|"Inventory"|"Purchases"|"Customers"|"Suppliers"|"Expenses"|"Reports"|"Team"|"Settings";

const tabs:Tab[]=["Overview","POS","Inventory","Purchases","Customers","Suppliers","Expenses","Reports","Team","Settings"];
const icon:Record<Tab,string>={Overview:"▦",POS:"⊕",Inventory:"□",Purchases:"⇩",Customers:"♙",Suppliers:"⌂",Expenses:"↗",Reports:"⌁",Team:"♚",Settings:"⚙"};
const gh=(n:number)=>`GH₵${n.toLocaleString(undefined,{minimumFractionDigits:2})}`;
const emptyLine=():PurchaseLine=>({id:crypto.randomUUID(),name:"",sku:"",qty:1,cost:0,price:0,cat:"Jewelry"});
const DB_NAME="cflex-store";
const DB_VERSION=3;
const STORE="state";

function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function readState<T>(key:string,fallback:T):Promise<T>{try{const db=await openDb();return await new Promise<T>((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve((req.result??fallback) as T);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close()})}catch{return fallback}}
async function writeState(key:string,value:unknown){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});db.close()}
function fileToDataUrl(file:File,cb:(v:string)=>void){const reader=new FileReader();reader.onload=()=>{const raw=String(reader.result||"");const img=new Image();img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");if(!ctx)return cb(raw);ctx.drawImage(img,0,0,canvas.width,canvas.height);cb(canvas.toDataURL("image/jpeg",.82))};img.onerror=()=>cb(raw);img.src=raw};reader.readAsDataURL(file)}

export default function Home(){
 const[tab,setTab]=useState<Tab>("Overview"),[online,setOnline]=useState(true),[items,setItems]=useState<Item[]>([]),[sales,setSales]=useState<Sale[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]),[profile,setProfile]=useState<StoreProfile>({name:"C.FLEX"}),[modal,setModal]=useState<"sale"|"inventory"|"purchase"|null>(null),[toast,setToast]=useState(""),[query,setQuery]=useState(""),[ready,setReady]=useState(false),[selectedItem,setSelectedItem]=useState<string|undefined>();
 useEffect(()=>{const f=()=>setOnline(navigator.onLine);f();addEventListener("online",f);addEventListener("offline",f);return()=>{removeEventListener("online",f);removeEventListener("offline",f)}},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{(async()=>{const[a,b,c,d]=await Promise.all([readState<Item[]>("items",[]),readState<Sale[]>("sales",[]),readState<Purchase[]>("purchases",[]),readState<StoreProfile>("profile",{name:"C.FLEX"})]);setItems(Array.isArray(a)?a:[]);setSales(Array.isArray(b)?b:[]);setPurchases(Array.isArray(c)?c:[]);if(d?.name)setProfile(d);setReady(true)})()},[]);
 useEffect(()=>{if(!ready)return;writeState("sales",sales).catch(()=>setToast("Could not save sales on this device"))},[sales,ready]);
 useEffect(()=>{if(!ready)return;writeState("profile",profile).catch(()=>setToast("Could not save store profile"))},[profile,ready]);

 const revenue=sales.reduce((a,s)=>a+s.total,0),cogs=sales.reduce((a,s)=>a+(items.find(i=>i.id===s.itemId)?.cost||0)*s.qty,0),low=items.filter(i=>i.stock<=i.reorder),pending=sales.filter(s=>!s.synced).length;
 const visible=items.filter(i=>(i.name+i.sku+i.cat).toLowerCase().includes(query.toLowerCase()));
 const sync=async()=>{if(!online)return setToast("Offline records are safe and waiting");setSales(v=>v.map(s=>({...s,synced:true})));setToast("Everything is synced")};
 const openSale=(id?:string)=>{if(!items.length)return setToast("Add inventory before recording a sale");setSelectedItem(id);setModal("sale")};
 const saveItems=async(next:Item[],success:string)=>{try{await writeState("items",next);setItems(next);setToast(success)}catch{setToast("Inventory could not be saved. Try a smaller image or free device storage.")}};
 const addInventory=async(lines:PurchaseLine[])=>{const added=lines.map(l=>({id:crypto.randomUUID(),name:l.name.trim(),sku:l.sku.trim(),cat:l.cat.trim()||"Uncategorized",stock:l.qty,reorder:5,cost:l.cost,price:l.price,location:"Main Store",image:l.image}));const next=[...added,...items];await saveItems(next,`${added.length} inventory item${added.length===1?"":"s"} saved`);setModal(null)};
 const savePurchase=async(p:Purchase)=>{const next=[p,...purchases];try{await writeState("purchases",next);setPurchases(next);setModal(null);setToast(`Purchase saved with ${p.lines.length} item${p.lines.length===1?"":"s"}`)}catch{setToast("Purchase could not be saved. Try smaller product images.")}};
 const receivePurchase=async(p:Purchase)=>{if(p.status==="Received")return;const added=p.lines.map(l=>({id:crypto.randomUUID(),name:l.name,sku:l.sku,cat:l.cat,stock:l.qty,reorder:5,cost:l.cost,price:l.price,location:"Main Store",image:l.image}));const nextItems=[...added,...items],nextPurchases=purchases.map(x=>x.id===p.id?{...x,status:"Received" as const}:x);try{await Promise.all([writeState("items",nextItems),writeState("purchases",nextPurchases)]);setItems(nextItems);setPurchases(nextPurchases);setToast("Purchase received into inventory with product images")}catch{setToast("Could not receive this purchase into inventory")}};

 return <main><aside><Brand profile={profile}/><nav>{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>{setTab(t);setQuery("")}} key={t}><i>{icon[t]}</i>{t}{t==="Inventory"&&low.length>0&&<em>{low.length}</em>}</button>)}</nav><div className="user"><b>SO</b><span><strong>Store Owner</strong><small>Owner · Main Store</small></span></div></aside><section className="work"><header><div className="mobile"><Brand profile={profile} compact/></div><span className={online?"status":"status offline"}>● {online?"Online · Saved":`Offline · ${pending} queued`}</span><button onClick={sync}>↻ Sync now</button></header><div className="content">
 {tab==="Overview"&&<><Title title="Good morning." sub={`Here’s how ${profile.name} is performing today.`} action="＋ Record sale" click={()=>openSale()}/><div className="stats"><Stat name="Today’s sales" value={gh(revenue)} note={sales.length?"Current recorded sales":"No sales recorded yet"}/><Stat name="Gross profit" value={gh(revenue-cogs)} note={revenue?`${Math.round((revenue-cogs)/revenue*100)}% margin`:"No sales yet"}/><Stat name="Stock value" value={gh(items.reduce((a,i)=>a+i.stock*i.cost,0))} note={`${items.reduce((a,i)=>a+i.stock,0)} units on hand`}/><Stat name="Needs attention" value={`${low.length} items`} note="Low stock or pending"/></div><div className="twocol"><Panel title="Sales overview"><div className="chart">{[45,68,55,83,64,92,76].map((h,i)=><span key={i} style={{height:h+"%"}}><small>{"SMTWTFS"[i]}</small></span>)}</div></Panel><Panel title="Low stock">{low.length?low.map(i=><div className="stock" key={i.id}>{i.image?<img src={i.image} alt={i.name}/>:<b>{i.cat[0]}</b>}<span><strong>{i.name}</strong><small>{i.sku} · {i.location}</small></span><em>{i.stock} left</em></div>):<p>No low-stock items.</p>}</Panel></div><Sales sales={sales}/></>}
 {tab==="Inventory"&&<><Title title="Inventory" sub="Products and photos are saved immediately after you add them." action="＋ Quick inventory" click={()=>setModal("inventory")}/><div className="tools"><input placeholder="Search name, SKU, barcode or category…" value={query} onChange={e=>setQuery(e.target.value)}/><button>Category⌄</button><button>▣ Scan barcode</button></div><div className="panel scroll"><div className="table inventory"><div>Product</div><div>Category</div><div>Location</div><div>Stock</div><div>Cost</div><div>Price</div>{visible.flatMap(i=>[<span className="productcell" key={i.id+"a"}>{i.image?<img src={i.image} alt={i.name}/>:<b className="thumb">{i.cat[0]}</b>}<span><b>{i.name}</b><small>{i.sku}</small></span></span>,<span key={i.id+"b"}>{i.cat}</span>,<span key={i.id+"c"}>{i.location}</span>,<span key={i.id+"d"}><em className={i.stock<=i.reorder?"warn":"ok"}>{i.stock} units</em></span>,<span key={i.id+"e"}>{gh(i.cost)}</span>,<strong key={i.id+"f"}>{gh(i.price)}</strong>])}</div>{!visible.length&&<p>No products yet. Use “Quick inventory” to add one or several products.</p>}</div></>}
 {tab==="Purchases"&&<><Title title="Purchases" sub="Each purchase line keeps its own product photo and values." action="＋ New purchase" click={()=>setModal("purchase")}/><div className="purchaseList">{purchases.length?purchases.map(p=><Panel key={p.id} title={`${p.supplier||"Supplier"} · ${p.id}`}><div className="purchaseMeta"><span>{p.tracking||"No tracking number"}</span><em className={p.status==="Received"?"ok":"warn"}>{p.status}</em></div>{p.lines.map(l=><div className="purchaseLine" key={l.id}>{l.image?<img src={l.image} alt={l.name}/>:<b>{l.cat[0]}</b>}<span><strong>{l.name}</strong><small>{l.sku} · {l.qty} pcs · {gh(l.cost)} each</small></span></div>)}{p.status!=="Received"&&<button className="receive" onClick={()=>receivePurchase(p)}>Receive all into inventory →</button>}</Panel>):<div className="panel"><p>No purchases yet. Create a purchase and add all items in one entry.</p></div>}</div></>}
 {tab==="POS"&&<><Title title="Point of Sale" sub="Visual product catalog — tap any product to sell it." action="＋ New sale" click={()=>openSale()}/><div className="tools posTools"><input placeholder="Search catalog by product, SKU or category…" value={query} onChange={e=>setQuery(e.target.value)}/><button>▣ Scan barcode</button></div><div className="products catalog">{visible.length?visible.map(i=><button className="productCard" key={i.id} onClick={()=>openSale(i.id)} disabled={i.stock<=0}><div className="catalogImage">{i.image?<img src={i.image} alt={i.name}/>:<b>{i.cat[0]}</b>}{i.stock<=0&&<span>Out of stock</span>}</div><div className="catalogInfo"><strong>{i.name}</strong><em>{gh(i.price)}</em><small>{i.stock} available · {i.cat}</small></div></button>):<p>No matching products in the catalog.</p>}</div><Sales sales={sales}/></>}
 {tab==="Settings"&&<><Title title="Settings" sub="Store identity, locations, currencies, barcode and sync." action="Save automatically" click={()=>setToast("Settings save automatically")}/><StoreSettings profile={profile} setProfile={setProfile}/><Module tab={tab}/></>}
 {!["Overview","Inventory","POS","Purchases","Settings"].includes(tab)&&<Module tab={tab}/>}</div><nav className="bottom">{(["Overview","POS","Inventory","Purchases","Reports"] as Tab[]).map(t=><button className={tab===t?"active":""} onClick={()=>{setTab(t);setQuery("")}} key={t}><i>{icon[t]}</i><small>{t}</small></button>)}</nav></section>
 {modal==="sale"&&items.length>0&&<SaleModal items={items} initialId={selectedItem} online={online} close={()=>setModal(null)} save={async s=>{const nextItems=items.map(i=>i.id===s.itemId?{...i,stock:i.stock-s.qty}:i);try{await writeState("items",nextItems);setItems(nextItems);setSales(v=>[s,...v]);setModal(null);setToast(online?"Sale completed and stock saved":"Sale saved offline and queued")}catch{setToast("Sale could not update inventory")}}}/>} {modal==="inventory"&&<MultiItemModal title="Quick inventory" close={()=>setModal(null)} save={addInventory}/>} {modal==="purchase"&&<PurchaseModal close={()=>setModal(null)} save={savePurchase}/>} {toast&&<div className="toast">✓ {toast}</div>}</main>
}

function Brand({profile,compact=false}:{profile:StoreProfile;compact?:boolean}){return <div className={compact?"brand compact":"brand"}>{profile.logo?<img src={profile.logo} alt="Store logo"/>:<b>{profile.name.trim().charAt(0)||"S"}</b>}<span><strong>{profile.name}</strong>{!compact&&<small>STORE MANAGER</small>}</span></div>}
function Title({title,sub,action,click}:{title:string;sub:string;action:string;click:()=>void}){return <div className="title"><div><small>Store Manager</small><h1>{title}</h1><p>{sub}</p></div><button onClick={click}>{action}</button></div>}
function Stat({name,value,note}:{name:string;value:string;note:string}){return <article><small>{name}</small><h2>{value}</h2><p>{note}</p></article>}
function Panel(p:{title:string;children:React.ReactNode}){return <section className="panel"><h3>{p.title}</h3>{p.children}</section>}
function Sales({sales}:{sales:Sale[]}){return <Panel title="Recent sales">{sales.length?<div className="table sales"><div>Sale</div><div>Product</div><div>Customer</div><div>Payment</div><div>Status</div><div>Total</div>{sales.map(s=>[<span key={s.id+1}><b>{s.id}</b><small>{s.time}</small></span>,<span key={s.id+2}>{s.item} × {s.qty}</span>,<span key={s.id+3}>{s.customer}</span>,<span key={s.id+4}>{s.payment}</span>,<span key={s.id+5}><em className={s.synced?"ok":"warn"}>{s.synced?"Synced":"Queued"}</em></span>,<strong key={s.id+6}>{gh(s.total)}</strong>])}</div>:<p>No sales recorded yet.</p>}</Panel>}
function Module({tab}:{tab:Tab}){const map:Record<string,[string,string[]]>={Customers:["Profiles, credit, history and WhatsApp details.",["Customer directory","Balances & credit","Purchase history","Loyalty groups"]],Suppliers:["Compare cost, lead time, quality and category.",["Supplier registry","Performance score","Source evidence","Price history"]],Expenses:["Operating costs separate from inventory value.",["Operating expenses","Logistics","Rent & utilities","Payroll"]],Reports:["Sales and stock movements turned into decisions.",["Profit & loss","Best sellers","Slow stock","Restock forecast"]],Team:["Role-based access and a complete audit trail.",["Owner","Manager","Cashier","Activity log"]],Settings:["Warehouses, currencies, tax, barcode and sync.",["Locations & bins","GHS · CNY · USD · XOF","Barcode rules","Backup & sync"]],Purchases:["Purchases",[]],Overview:["",[]],POS:["",[]],Inventory:["",[]]};const d=map[tab];return <div className="modules">{d[1].map(x=><Panel key={x} title={x}><p>Connected to inventory, finance and audit trail.</p><button>Open →</button></Panel>)}</div>}
function StoreSettings({profile,setProfile}:{profile:StoreProfile;setProfile:(p:StoreProfile)=>void}){return <Panel title="Store name & logo"><div className="storeSettings"><div className="logoPreview">{profile.logo?<img src={profile.logo} alt="Store logo"/>:<b>{profile.name.charAt(0)||"S"}</b>}</div><div><label>Store name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Store logo<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)fileToDataUrl(f,v=>setProfile({...profile,logo:v}))}}/></label><small>The store name and logo are saved on this device and stay in the original header/sidebar position.</small></div></div></Panel>}
function SaleModal({items,initialId,online,close,save}:{items:Item[];initialId?:string;online:boolean;close:()=>void;save:(s:Sale)=>void}){const start=initialId&&items.some(i=>i.id===initialId)?initialId:items.find(i=>i.stock>0)?.id||items[0].id;const[id,setId]=useState(start),[qty,setQty]=useState(1),[payment,setPayment]=useState("Mobile Money"),[customer,setCustomer]=useState("Walk-in");const item=items.find(i=>i.id===id)!;return <Modal title="Record sale" close={close}><form onSubmit={(e:FormEvent)=>{e.preventDefault();if(qty>0&&qty<=item.stock)save({id:`S-${Date.now().toString().slice(-6)}`,itemId:id,item:item.name,qty,total:item.price*qty,payment,customer,time:new Date().toLocaleString(),synced:online})}}><label>Product<select value={id} onChange={e=>{setId(e.target.value);setQty(1)}}>{items.map(i=><option value={i.id} key={i.id} disabled={i.stock<=0}>{i.name} — {i.stock} available</option>)}</select></label><div className="form2"><label>Quantity<input type="number" min="1" max={Math.max(1,item.stock)} value={qty} onChange={e=>setQty(+e.target.value)}/></label><label>Payment<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Mobile Money</option><option>Cash</option><option>Card</option><option>Store Credit</option></select></label></div><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)}/></label><h3>Total <b>{gh(item.price*qty)}</b></h3><button className="save" disabled={item.stock<=0}>Complete sale</button></form></Modal>}
function MultiItemModal({title,close,save}:{title:string;close:()=>void;save:(l:PurchaseLine[])=>void}){const[lines,setLines]=useState<PurchaseLine[]>([emptyLine()]),[saving,setSaving]=useState(false);const patch=(id:string,p:Partial<PurchaseLine>)=>setLines(v=>v.map(x=>x.id===id?{...x,...p}:x));return <Modal title={title} close={close} wide><form onSubmit={async e=>{e.preventDefault();const valid=lines.filter(x=>x.name.trim()&&x.sku.trim()&&x.qty>0);if(valid.length){setSaving(true);await save(valid);setSaving(false)}}}><div className="multiHead"><b>Products</b><button type="button" onClick={()=>setLines(v=>[...v,emptyLine()])}>＋ Add another item</button></div>{lines.map((l,i)=><ProductEntry key={l.id} line={l} index={i} patch={patch} remove={()=>setLines(v=>v.filter(x=>x.id!==l.id))} removable={lines.length>1}/>)}<button className="save" disabled={saving}>{saving?"Saving inventory…":`Add ${lines.length} item${lines.length===1?"":"s"} to inventory`}</button></form></Modal>}
function PurchaseModal({close,save}:{close:()=>void;save:(p:Purchase)=>void}){const[supplier,setSupplier]=useState(""),[tracking,setTracking]=useState(""),[lines,setLines]=useState<PurchaseLine[]>([emptyLine()]),[saving,setSaving]=useState(false);const patch=(id:string,p:Partial<PurchaseLine>)=>setLines(v=>v.map(x=>x.id===id?{...x,...p}:x));return <Modal title="New purchase" close={close} wide><form onSubmit={async e=>{e.preventDefault();const valid=lines.filter(x=>x.name.trim()&&x.sku.trim()&&x.qty>0);if(valid.length){setSaving(true);await save({id:`PO-${Date.now().toString().slice(-6)}`,supplier,tracking,status:"Ordered",time:new Date().toLocaleString(),lines:valid});setSaving(false)}}}><div className="form2"><label>Supplier<input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Supplier name"/></label><label>Tracking number<input value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="Optional"/></label></div><div className="multiHead"><b>Purchase items</b><button type="button" onClick={()=>setLines(v=>[...v,emptyLine()])}>＋ Add another item</button></div>{lines.map((l,i)=><ProductEntry key={l.id} line={l} index={i} patch={patch} remove={()=>setLines(v=>v.filter(x=>x.id!==l.id))} removable={lines.length>1}/>)}<button className="save" disabled={saving}>{saving?"Saving purchase…":`Save purchase (${lines.length} items)`}</button></form></Modal>}
function ProductEntry({line:l,index,patch,remove,removable}:{line:PurchaseLine;index:number;patch:(id:string,p:Partial<PurchaseLine>)=>void;remove:()=>void;removable:boolean}){return <div className="multiLine"><div className="lineNo">{index+1}</div><label>Image<div className="imagePick">{l.image?<img src={l.image} alt={l.name||"Product"}/>:<span>＋ Photo</span>}<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)fileToDataUrl(f,v=>patch(l.id,{image:v}))}}/></div></label><div className="lineFields"><div className="form2"><label>Product name<input required value={l.name} onChange={e=>patch(l.id,{name:e.target.value})}/></label><label>SKU / barcode<input required value={l.sku} onChange={e=>patch(l.id,{sku:e.target.value})}/></label></div><div className="form4"><label>Qty<input type="number" min="1" value={l.qty} onChange={e=>patch(l.id,{qty:+e.target.value})}/></label><label>Cost<input type="number" min="0" step="0.01" value={l.cost} onChange={e=>patch(l.id,{cost:+e.target.value})}/></label><label>Price<input type="number" min="0" step="0.01" value={l.price} onChange={e=>patch(l.id,{price:+e.target.value})}/></label><label>Category<input value={l.cat} onChange={e=>patch(l.id,{cat:e.target.value})}/></label></div></div>{removable&&<button className="remove" type="button" onClick={remove}>×</button>}</div>}
function Modal({title,close,children,wide=false}:{title:string;close:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="overlay"><div className={wide?"modal wide":"modal"}><button className="x" onClick={close}>×</button><h2>{title}</h2><p>Each item keeps its own image, SKU, quantity, cost and selling price.</p>{children}</div></div>}
